/**
 * @hidden
 */
/**
 *
 */
import XEUtils from './ctor'

// object
export * from './assign'
export * from './objectEach'
export * from './lastObjectEach'
export * from './objectMap'
export * from './merge'

// array
export * from './map'
export * from './some'
export * from './every'
export * from './includeArrays'
export * from './arrayEach'
export * from './lastArrayEach'
export * from './uniq'
export * from './union'
export * from './toArray'
export * from './sortBy'
export * from './orderBy'
export * from './shuffle'
export * from './sample'
export * from './slice'
export * from './filter'
export * from './findKey'
export * from './includes'
export * from './find'
export * from './findLast'
export * from './reduce'
export * from './copyWithin'
export * from './chunk'
export * from './zip'
export * from './unzip'
export * from './zipObject'
export * from './pluck'
export * from './invoke'
export * from './toArrayTree'
export * from './toTreeArray'
export * from './findTree'
export * from './eachTree'
export * from './mapTree'
export * from './filterTree'
export * from './searchTree'
export * from './arrayIndexOf'
export * from './arrayLastIndexOf'

// base
export * from './hasOwnProp'
export * from './isArray'
export * from './isNull'
export * from './isNaN'
export * from './isUndefined'
export * from './isFunction'
export * from './isObject'
export * from './isString'
export * from './isPlainObject'
export * from './isLeapYear'
export * from './isDate'
export * from './eqNull'
export * from './each'
export * from './forOf'
export * from './lastForOf'
export * from './indexOf'
export * from './lastIndexOf'
export * from './keys'
export * from './values'
export * from './clone'
export * from './cloneDeep'
export * from './getSize'
export * from './lastEach'
export * from './remove'
export * from './clear'
export * from './isFinite'
export * from './isFloat'
export * from './isInteger'
export * from './isBoolean'
export * from './isNumber'
export * from './isRegExp'
export * from './isError'
export * from './isTypeError'
export * from './isEmpty'
export * from './isEmptyValue'
export * from './isSymbol'
export * from './isArguments'
export * from './isElement'
export * from './isDocument'
export * from './isWindow'
export * from './isFormData'
export * from './isMap'
export * from './isWeakMap'
export * from './isSet'
export * from './isWeakSet'
export * from './isMatch'
export * from './isEqual'
export * from './isEqualWith'
export * from './getType'
export * from './uniqueId'
export * from './findIndexOf'
export * from './findLastIndexOf'
export * from './toStringJSON'
export * from './toJSONString'
export * from './toFixed'
export * from './entries'
export * from './pick'
export * from './omit'
export * from './first'
export * from './last'
export * from './has'
export * from './get'
export * from './set'
export * from './groupBy'
export * from './countBy'
export * from './range'
export * from './destructuring'

// number
export * from './random'
export * from './max'
export * from './min'
export * from './commafy'
export * from './round'
export * from './ceil'
export * from './floor'
export * from './toInteger'
export * from './toNumber'
export * from './add'
export * from './subtract'
export * from './multiply'
export * from './divide'
export * from './sum'
export * from './mean'

// date
export * from './getWhatYear'
export * from './getWhatMonth'
export * from './getWhatDay'
export * from './toStringDate'
export * from './toDateString'
export * from './now'
export * from './timestamp'
export * from './isValidDate'
export * from './isDateSame'
export * from './getWhatWeek'
export * from './getYearDay'
export * from './getYearWeek'
export * from './getMonthWeek'
export * from './getDayOfYear'
export * from './getDayOfMonth'
export * from './getDateDiff'

// string
export * from './padEnd'
export * from './padStart'
export * from './repeat'
export * from './trim'
export * from './trimRight'
export * from './trimLeft'
export * from './escape'
export * from './unescape'
export * from './camelCase'
export * from './kebabCase'
export * from './startsWith'
export * from './endsWith'
export * from './template'
export * from './toFormatString'
export * from './toString'
export * from './toValueString'
export * from './checkPass'

// function
export * from './property'
export * from './bind'
export * from './once'
export * from './after'
export * from './before'
export * from './throttle'
export * from './debounce'
export * from './delay'

// url
export * from './unserialize'
export * from './serialize'
export * from './parseUrl'
export { objectToUrlParam } from './objectToUrlParam'

// Web
export * from './getBaseURL'
export * from './locat'
export * from './cookie'
export * from './browse'

// custom
export * from './moment'
export * from './webStorages'
export * from './sorter'
export * from './pinyin'
export * from './getLodop'
export * from './element'
export * from './data'
export * from './cookies'
export * from './browser'
export * from './crypto'
export * from './clipboard'

export * from './validator'

export * from './data'

export * from './hkIdVerify'

export default XEUtils
export { stringToMoment } from './stringToMoment'
export { stringArrayToMomentArray } from './stringArrayToMomentArray'
export { momentToString } from './momentToString'
export { momentArrayToStringArray } from './momentArrayToStringArray'
export { getMoment } from './getMoment'
export { dateToMoment } from './dateToMoment'
export { dateToString } from './dateToString'
export { momentToDate } from './momentToDate'
export { isDateString } from './isDateString'
export { isTime } from './isTime'
export { isDateTime } from './isDateTime'
export { getCurDate } from './getCurDate'
export { getCurDateMonth } from './getCurDateMonth'
export { baseGetCurDateTime } from './baseGetCurDateTime'
export { getCurDateTime } from './getCurDateTime'
export { getCurDateFullTime } from './getCurDateFullTime'
export { getCurQuarter } from './getCurQuarter'
export { getCurIssue } from './getCurIssue'
export { getCurDateYear } from './getCurDateYear'
export { StringToDate } from './stringToDate'
export { dateDiff } from './dateDiff'
export { isIE } from './isIE'
export { IEVersion } from './IEVersion'
export { notSupported } from './notSupported'
export { isIE9 } from './isIE9'
export { isIE10 } from './isIE10'
export { isIE11 } from './isIE11'
export { isChrome } from './isChrome'
export { isFireFox } from './isFireFox'
export { isSafari } from './isSafari'
export { isSilversea } from './isSilversea'
export { getBrowserInfo } from './getBrowserInfo'
export { getCurrentSystemInfo } from './getCurrentSystemInfo'
export { setCookie } from './setCookie'
export { getCookie } from './getCookie'
export { getToken } from './getToken'
export { sortWithLetter } from './sortWithLetter'
export { sortWithNumber } from './sortWithNumber'
export { sortWithCharacter } from './sortWithCharacter'
export { getStorage } from './getStorage'
export { uuid } from './uuid'
export { uuidV4 } from './uuidV4'
